# Generated by Django 4.1.2 on 2022-10-22 18:56

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المتجر')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('img', models.ImageField(blank=True, null=True, upload_to='blogTypes/img/')),
                ('img_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الصورة')),
                ('keyword', models.TextField(blank=True, null=True, verbose_name='كلمات مفتاحية')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم قسم الخدمة')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('img', models.ImageField(blank=True, null=True, upload_to='blogTypes/img/')),
                ('img_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الصورة')),
                ('keyword', models.TextField(blank=True, null=True, verbose_name='كلمات مفتاحية')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.storetypes', verbose_name='المتجر')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان المقالة')),
                ('desc', models.TextField(null=True, verbose_name='وصف')),
                ('article_img', models.ImageField(null=True, upload_to='article/img/%Y/%m/%d')),
                ('img_desc', models.CharField(max_length=255, null=True, verbose_name='وصف الصورة')),
                ('article', froala_editor.fields.FroalaField()),
                ('keyword', models.TextField(null=True, verbose_name='كلمات مفتاحية')),
                ('is_from_url', models.BooleanField(default=False, verbose_name='هل رابط تحميل الخدمة من الخارج')),
                ('service_url', models.CharField(blank=True, max_length=255, verbose_name='رابط الخدمة')),
                ('is_from_local', models.BooleanField(default=False, verbose_name='هل تريد رفع الخدمة محليا')),
                ('service_file', models.FileField(blank=True, upload_to='service/files/%Y/%m/', verbose_name='رفع ملف')),
                ('publish_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('service_Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.servicetypes', verbose_name='نوع الخدمة')),
                ('storeTypes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.storetypes', verbose_name='نوع المتجر')),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
