# Generated by Django 4.1.2 on 2022-10-22 19:01

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_product_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='article_ar',
            field=froala_editor.fields.FroalaField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='article_en',
            field=froala_editor.fields.FroalaField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='desc_ar',
            field=models.TextField(null=True, verbose_name='وصف'),
        ),
        migrations.AddField(
            model_name='services',
            name='desc_en',
            field=models.TextField(null=True, verbose_name='وصف'),
        ),
        migrations.AddField(
            model_name='services',
            name='img_desc_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='وصف الصورة'),
        ),
        migrations.AddField(
            model_name='services',
            name='img_desc_en',
            field=models.CharField(max_length=255, null=True, verbose_name='وصف الصورة'),
        ),
        migrations.AddField(
            model_name='services',
            name='keyword_ar',
            field=models.TextField(null=True, verbose_name='كلمات مفتاحية'),
        ),
        migrations.AddField(
            model_name='services',
            name='keyword_en',
            field=models.TextField(null=True, verbose_name='كلمات مفتاحية'),
        ),
        migrations.AddField(
            model_name='services',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان المقالة'),
        ),
        migrations.AddField(
            model_name='services',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان المقالة'),
        ),
        migrations.AddField(
            model_name='servicetypes',
            name='desc_ar',
            field=models.TextField(blank=True, null=True, verbose_name='وصف'),
        ),
        migrations.AddField(
            model_name='servicetypes',
            name='desc_en',
            field=models.TextField(blank=True, null=True, verbose_name='وصف'),
        ),
        migrations.AddField(
            model_name='servicetypes',
            name='img_desc_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الصورة'),
        ),
        migrations.AddField(
            model_name='servicetypes',
            name='img_desc_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الصورة'),
        ),
        migrations.AddField(
            model_name='servicetypes',
            name='keyword_ar',
            field=models.TextField(blank=True, null=True, verbose_name='كلمات مفتاحية'),
        ),
        migrations.AddField(
            model_name='servicetypes',
            name='keyword_en',
            field=models.TextField(blank=True, null=True, verbose_name='كلمات مفتاحية'),
        ),
        migrations.AddField(
            model_name='servicetypes',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='اسم قسم الخدمة'),
        ),
        migrations.AddField(
            model_name='servicetypes',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='اسم قسم الخدمة'),
        ),
        migrations.AddField(
            model_name='storetypes',
            name='desc_ar',
            field=models.TextField(blank=True, null=True, verbose_name='وصف'),
        ),
        migrations.AddField(
            model_name='storetypes',
            name='desc_en',
            field=models.TextField(blank=True, null=True, verbose_name='وصف'),
        ),
        migrations.AddField(
            model_name='storetypes',
            name='img_desc_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الصورة'),
        ),
        migrations.AddField(
            model_name='storetypes',
            name='img_desc_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الصورة'),
        ),
        migrations.AddField(
            model_name='storetypes',
            name='keyword_ar',
            field=models.TextField(blank=True, null=True, verbose_name='كلمات مفتاحية'),
        ),
        migrations.AddField(
            model_name='storetypes',
            name='keyword_en',
            field=models.TextField(blank=True, null=True, verbose_name='كلمات مفتاحية'),
        ),
        migrations.AddField(
            model_name='storetypes',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='اسم المتجر'),
        ),
        migrations.AddField(
            model_name='storetypes',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='اسم المتجر'),
        ),
    ]
