# Generated by Django 4.1.2 on 2022-10-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_services_article_ar_services_article_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='service_version',
            field=models.CharField(max_length=255, null=True, verbose_name='اصدار الخدمة'),
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_Type',
        ),
        migrations.AddField(
            model_name='services',
            name='service_Type',
            field=models.ManyToManyField(to='store.servicetypes', verbose_name='نوع الخدمة'),
        ),
    ]
