# Generated by Django 4.1.2 on 2022-10-22 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_services_last_update_services_service_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اصدار الخدمة'),
        ),
        migrations.CreateModel(
            name='ServicesDownloads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.services', verbose_name='الخدمة')),
            ],
        ),
    ]
