# Generated by Django 4.1.2 on 2022-10-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_services_service_version_servicesdownloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesdownloads',
            name='downloaded_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
