# Generated by Django 4.1.2 on 2022-10-22 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_servicesdownloads_downloaded_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('visited_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.services', verbose_name='الخدمة')),
            ],
        ),
    ]
