# Generated by Django 4.1.2 on 2022-10-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_serviceviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='issued',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاصلي التي  نشرت لاول مرة على الانترنت'),
        ),
    ]
