# Generated by Django 4.1.2 on 2022-10-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_services_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='show_contuct_button',
            field=models.BooleanField(default=True, verbose_name='اظهار زر التواصل معنا الخدمة'),
        ),
        migrations.AddField(
            model_name='services',
            name='show_download_button',
            field=models.BooleanField(default=True, verbose_name='اظهار زر تحميل الخدمة'),
        ),
    ]
