# Generated by Django 4.1.2 on 2022-10-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_services_show_contuct_button_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='اخفاء الخدمة على الموقع'),
        ),
        migrations.AlterField(
            model_name='services',
            name='show_contuct_button',
            field=models.BooleanField(default=False, verbose_name='اظهار زر التواصل معنا الخدمة'),
        ),
    ]
