# Generated by Django 4.1.2 on 2022-10-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_services_is_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='file_size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='حجم الملف المراد تنزيله'),
        ),
        migrations.AlterField(
            model_name='services',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='هل الخدمة مفعلة ليظهر على الموقع'),
        ),
    ]
