# Generated by Django 4.1.2 on 2022-10-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_services_file_size_alter_services_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='download_btn_get_without_getDownloadsLink',
            field=models.CharField(blank=True, max_length=255, verbose_name='اذهب الى قطعة من الصفحة'),
        ),
        migrations.AddField(
            model_name='services',
            name='is_download_btn_get_without_getDownloadsLink',
            field=models.BooleanField(default=False, verbose_name='#btn اذهب الى قطعة من الصفحة مثلا '),
        ),
    ]
