# Generated by Django 4.0 on 2022-11-17 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_services_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='is_visible_to_the_user',
            field=models.BooleanField(default=True, verbose_name='اظهار الخدمة عند المستخدم'),
        ),
        migrations.AddField(
            model_name='services',
            name='save_as_draft',
            field=models.BooleanField(default=False, verbose_name='حفظ كمسودة'),
        ),
        migrations.CreateModel(
            name='WaitForAccept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.services', verbose_name='الخدمة')),
            ],
        ),
    ]
