# Generated by Django 4.0 on 2022-11-17 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_alter_user_username'),
        ('store', '0015_services_is_visible_to_the_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='article_img',
            field=models.ImageField(blank=True, null=True, upload_to='article/img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='services',
            name='img_desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الصورة'),
        ),
        migrations.AlterField(
            model_name='services',
            name='img_desc_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الصورة'),
        ),
        migrations.AlterField(
            model_name='services',
            name='img_desc_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الصورة'),
        ),
        migrations.AlterField(
            model_name='services',
            name='keyword',
            field=models.TextField(blank=True, null=True, verbose_name='كلمات مفتاحية'),
        ),
        migrations.AlterField(
            model_name='services',
            name='keyword_ar',
            field=models.TextField(blank=True, null=True, verbose_name='كلمات مفتاحية'),
        ),
        migrations.AlterField(
            model_name='services',
            name='keyword_en',
            field=models.TextField(blank=True, null=True, verbose_name='كلمات مفتاحية'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_Type',
            field=models.ManyToManyField(blank=True, to='store.ServiceTypes', verbose_name='نوع الخدمة'),
        ),
        migrations.AlterField(
            model_name='services',
            name='storeTypes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.storetypes', verbose_name='نوع المتجر'),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='عنوان المقالة'),
        ),
        migrations.AlterField(
            model_name='services',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان المقالة'),
        ),
        migrations.AlterField(
            model_name='services',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان المقالة'),
        ),
        migrations.AlterField(
            model_name='services',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user', verbose_name='الناشر'),
        ),
    ]
