# Generated by Django 4.0 on 2022-11-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_services_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='issued',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاصلي التي  نشرت لاول مرة على الانترنت'),
        ),
    ]
