# Generated by Django 4.0 on 2022-11-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_services_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='وصف'),
        ),
        migrations.AlterField(
            model_name='services',
            name='desc_ar',
            field=models.TextField(blank=True, null=True, verbose_name='وصف'),
        ),
        migrations.AlterField(
            model_name='services',
            name='desc_en',
            field=models.TextField(blank=True, null=True, verbose_name='وصف'),
        ),
    ]
