# Generated by Django 4.0 on 2022-11-17 23:45

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_services_desc_alter_services_desc_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='article',
            field=froala_editor.fields.FroalaField(blank=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='article_ar',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='article_en',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
