# Generated by Django 4.0 on 2022-11-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_services_article_alter_services_article_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='file_size_format',
            field=models.CharField(blank=True, choices=[('0', 'TB'), ('1', 'GB'), ('2', 'MB'), ('3', 'KB'), ('4', 'Byte')], max_length=255, null=True, verbose_name='صغة حجم الملف المراد تنزيله'),
        ),
    ]
