# Generated by Django 4.0 on 2022-11-18 03:33

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_alter_user_username'),
        ('store', '0022_services_file_size_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditedServicesWaitForAccept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='عنوان المقالة')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('article_img', models.ImageField(blank=True, null=True, upload_to='article/img/%Y/%m/%d')),
                ('img_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الصورة')),
                ('article', froala_editor.fields.FroalaField(blank=True)),
                ('keyword', models.TextField(blank=True, null=True, verbose_name='كلمات مفتاحية')),
                ('is_from_url', models.BooleanField(default=False, verbose_name='هل رابط تحميل الخدمة من الخارج')),
                ('service_url', models.CharField(blank=True, max_length=255, verbose_name='رابط الخدمة')),
                ('is_from_local', models.BooleanField(default=False, verbose_name='هل تريد رفع الخدمة محليا')),
                ('is_download_btn_get_without_getDownloadsLink', models.BooleanField(default=False, verbose_name='#btn اذهب الى قطعة من الصفحة مثلا ')),
                ('download_btn_get_without_getDownloadsLink', models.CharField(blank=True, max_length=255, verbose_name='اذهب الى قطعة من الصفحة')),
                ('service_file', models.FileField(blank=True, upload_to='service/files/%Y/%m/', verbose_name='رفع ملف')),
                ('service_version', models.CharField(blank=True, max_length=255, null=True, verbose_name='اصدار الخدمة')),
                ('file_size', models.CharField(blank=True, max_length=255, null=True, verbose_name='حجم الملف المراد تنزيله')),
                ('file_size_format', models.CharField(blank=True, choices=[('0', 'TB'), ('1', 'GB'), ('2', 'MB'), ('3', 'KB'), ('4', 'Byte')], max_length=255, null=True, verbose_name='صغة حجم الملف المراد تنزيله')),
                ('issued', models.DateField(blank=True, null=True, verbose_name='تاريخ الاصلي التي  نشرت لاول مرة على الانترنت')),
                ('show_download_button', models.BooleanField(default=True, verbose_name='اظهار زر تحميل الخدمة')),
                ('show_contuct_button', models.BooleanField(default=False, verbose_name='اظهار زر التواصل معنا الخدمة')),
                ('publish_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.services', verbose_name='الخدمة المعدلة')),
                ('service_Type', models.ManyToManyField(blank=True, to='store.ServiceTypes', verbose_name='نوع الخدمة')),
                ('storeTypes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.storetypes', verbose_name='نوع المتجر')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user', verbose_name='الناشر')),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
