# Generated by Django 4.0 on 2022-11-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_editedserviceswaitforaccept'),
    ]

    operations = [
        migrations.AddField(
            model_name='editedserviceswaitforaccept',
            name='save_as_draft',
            field=models.BooleanField(default=False, verbose_name='حفظ كمسودة'),
        ),
    ]
