# Generated by Django 4.0 on 2022-11-18 04:04

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_editedserviceswaitforaccept_save_as_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='editedserviceswaitforaccept',
            name='article_ar',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editedserviceswaitforaccept',
            name='article_en',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editedserviceswaitforaccept',
            name='desc_ar',
            field=models.TextField(blank=True, null=True, verbose_name='وصف'),
        ),
        migrations.AddField(
            model_name='editedserviceswaitforaccept',
            name='desc_en',
            field=models.TextField(blank=True, null=True, verbose_name='وصف'),
        ),
        migrations.AddField(
            model_name='editedserviceswaitforaccept',
            name='img_desc_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الصورة'),
        ),
        migrations.AddField(
            model_name='editedserviceswaitforaccept',
            name='img_desc_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الصورة'),
        ),
        migrations.AddField(
            model_name='editedserviceswaitforaccept',
            name='keyword_ar',
            field=models.TextField(blank=True, null=True, verbose_name='كلمات مفتاحية'),
        ),
        migrations.AddField(
            model_name='editedserviceswaitforaccept',
            name='keyword_en',
            field=models.TextField(blank=True, null=True, verbose_name='كلمات مفتاحية'),
        ),
        migrations.AddField(
            model_name='editedserviceswaitforaccept',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان المقالة'),
        ),
        migrations.AddField(
            model_name='editedserviceswaitforaccept',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان المقالة'),
        ),
    ]
