# Generated by Django 4.0 on 2022-11-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_editedserviceswaitforaccept_article_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editedserviceswaitforaccept',
            name='modification_cancelled',
            field=models.BooleanField(default=False, verbose_name='تم الغاء التعديل'),
        ),
    ]
