# Generated by Django 4.1.3 on 2022-11-20 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_serviceviews_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceviews',
            old_name='country',
            new_name='country_code',
        ),
    ]
