# Generated by Django 4.1.3 on 2022-11-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_rename_country_serviceviews_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceviews',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='serviceviews',
            name='country_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='serviceviews',
            name='region',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
