# Generated by Django 4.1.3 on 2022-11-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_serviceviews_earn_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceviews',
            name='earn_count',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='ربحت من الزيارة'),
        ),
    ]
