# Generated by Django 4.1.3 on 2022-11-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_ar',
            field=models.TextField(null=True, verbose_name='الرسالة'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_en',
            field=models.TextField(null=True, verbose_name='الرسالة'),
        ),
    ]
