# Generated by Django 4.1.3 on 2022-11-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification_message_ar_notification_message_en'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-publish_date']},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_not_read_notification',
            field=models.BooleanField(default=False, verbose_name='انه لم يقراء الاشعارات بعد'),
        ),
    ]
