# Generated by Django 4.1.3 on 2022-11-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='الرصيد'),
        ),
    ]
