# Generated by Django 4.1.3 on 2022-11-21 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_userprofile_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Pending,, قيد الانتظار'), ('1', 'Approved,, وافق'), ('2', 'Complete,, مكتمل'), ('3', 'Cancelled,, ألغيت')], max_length=250, verbose_name='الحالة')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='سعر لكل زيارة')),
                ('withdrawal_method', models.CharField(choices=[('0', 'Pending,, قيد الانتظار'), ('1', 'Approved,, وافق'), ('2', 'Complete,, مكتمل'), ('3', 'Cancelled,, ألغيت')], max_length=250, verbose_name='الحالة')),
                ('withdraw_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ السحب')),
                ('desc', models.TextField(verbose_name='وصف')),
                ('is_completed', models.BooleanField(default=False, verbose_name='دفعت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
    ]
