# Generated by Django 4.1.3 on 2022-11-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_withdraw'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdraw',
            options={'ordering': ['-withdraw_date']},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='money',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='الرصيد'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='كمية السحب'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='withdrawal_method',
            field=models.CharField(choices=[('0', 'paypal')], max_length=250, verbose_name='نوع السحب'),
        ),
    ]
