# Generated by Django 4.1.3 on 2022-11-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userprofile_money_alter_withdraw_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='City',
            field=models.CharField(blank=True, choices=[('0', 'Pending,, قيد الانتظار'), ('1', 'Approved,, وافق'), ('2', 'Complete,, مكتمل'), ('3', 'Cancelled,, ألغيت')], max_length=250, null=True, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, choices=[('0', 'Pending,, قيد الانتظار'), ('1', 'Approved,, وافق'), ('2', 'Complete,, مكتمل'), ('3', 'Cancelled,, ألغيت')], max_length=250, null=True, verbose_name='العنوان1'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address2',
            field=models.CharField(blank=True, choices=[('0', 'Pending,, قيد الانتظار'), ('1', 'Approved,, وافق'), ('2', 'Complete,, مكتمل'), ('3', 'Cancelled,, ألغيت')], max_length=250, null=True, verbose_name='العنوان2'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, choices=[('0', 'Pending,, قيد الانتظار'), ('1', 'Approved,, وافق'), ('2', 'Complete,, مكتمل'), ('3', 'Cancelled,, ألغيت')], max_length=250, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, choices=[('0', 'Pending,, قيد الانتظار'), ('1', 'Approved,, وافق'), ('2', 'Complete,, مكتمل'), ('3', 'Cancelled,, ألغيت')], max_length=250, null=True, verbose_name='الولاية'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verified_email',
            field=models.BooleanField(default=False, verbose_name='انه لم يقراء الاشعارات بعد'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zip_code',
            field=models.CharField(blank=True, choices=[('0', 'Pending,, قيد الانتظار'), ('1', 'Approved,, وافق'), ('2', 'Complete,, مكتمل'), ('3', 'Cancelled,, ألغيت')], max_length=250, null=True, verbose_name='الرمز البريدي'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='money',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='الرصيد'),
        ),
    ]
