# Generated by Django 4.1.3 on 2022-11-23 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_city_userprofile_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='City',
            new_name='city',
        ),
    ]
