# Generated by Django 4.1.3 on 2022-11-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_city_userprofile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='العنوان1'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='العنوان2'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='الولاية'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='الرمز البريدي'),
        ),
    ]
