# Generated by Django 4.1.3 on 2022-11-23 14:48

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userprofile_countrys_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الالكتروني')),
                ('secrt', models.CharField(default=accounts.models.GenrateString, max_length=255, verbose_name='كملة سر التأكيد')),
                ('is_finshed', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
