# Generated by Django 4.1.3 on 2022-11-23 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_verifiedemail_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verifiedemail',
            old_name='secrt',
            new_name='secret',
        ),
    ]
