# Generated by Django 4.1.3 on 2022-11-24 15:50

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_resetpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='secret',
            field=models.CharField(default=accounts.models.GenrateString, max_length=255, unique=True, verbose_name='كملة سر التأكيد'),
        ),
        migrations.AlterField(
            model_name='verifiedemail',
            name='secret',
            field=models.CharField(default=accounts.models.GenrateString, max_length=255, unique=True, verbose_name='كملة سر التأكيد'),
        ),
    ]
