# Generated by Django 4.1.2 on 2022-10-21 20:33

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم قسم المقالة')),
                ('name_ar', models.CharField(max_length=255, null=True, verbose_name='اسم قسم المقالة')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='اسم قسم المقالة')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('desc_ar', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('desc_en', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('img', models.ImageField(blank=True, null=True, upload_to='blogTypes/img/')),
                ('img_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الصورة')),
                ('img_desc_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الصورة')),
                ('img_desc_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الصورة')),
                ('keyword', models.TextField(blank=True, null=True, verbose_name='كلمات مفتاحية')),
                ('keyword_ar', models.TextField(blank=True, null=True, verbose_name='كلمات مفتاحية')),
                ('keyword_en', models.TextField(blank=True, null=True, verbose_name='كلمات مفتاحية')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='blogTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المدونة')),
                ('name_ar', models.CharField(max_length=255, null=True, verbose_name='اسم المدونة')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='اسم المدونة')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('desc_ar', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('desc_en', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('img', models.ImageField(blank=True, null=True, upload_to='blogTypes/img/')),
                ('img_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الصورة')),
                ('img_desc_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الصورة')),
                ('img_desc_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الصورة')),
                ('keyword', models.TextField(blank=True, null=True, verbose_name='كلمات مفتاحية')),
                ('keyword_ar', models.TextField(blank=True, null=True, verbose_name='كلمات مفتاحية')),
                ('keyword_en', models.TextField(blank=True, null=True, verbose_name='كلمات مفتاحية')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ArticleType',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publish_date']},
        ),
        migrations.AddField(
            model_name='article',
            name='article_ar',
            field=froala_editor.fields.FroalaField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='article_en',
            field=froala_editor.fields.FroalaField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='article_img',
            field=models.ImageField(null=True, upload_to='article/img/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='article',
            name='desc',
            field=models.TextField(null=True, verbose_name='وصف'),
        ),
        migrations.AddField(
            model_name='article',
            name='desc_ar',
            field=models.TextField(null=True, verbose_name='وصف'),
        ),
        migrations.AddField(
            model_name='article',
            name='desc_en',
            field=models.TextField(null=True, verbose_name='وصف'),
        ),
        migrations.AddField(
            model_name='article',
            name='img_desc',
            field=models.CharField(max_length=255, null=True, verbose_name='وصف الصورة'),
        ),
        migrations.AddField(
            model_name='article',
            name='img_desc_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='وصف الصورة'),
        ),
        migrations.AddField(
            model_name='article',
            name='img_desc_en',
            field=models.CharField(max_length=255, null=True, verbose_name='وصف الصورة'),
        ),
        migrations.AddField(
            model_name='article',
            name='keyword',
            field=models.TextField(null=True, verbose_name='كلمات مفتاحية'),
        ),
        migrations.AddField(
            model_name='article',
            name='keyword_ar',
            field=models.TextField(null=True, verbose_name='كلمات مفتاحية'),
        ),
        migrations.AddField(
            model_name='article',
            name='keyword_en',
            field=models.TextField(null=True, verbose_name='كلمات مفتاحية'),
        ),
        migrations.AddField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان المقالة'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان المقالة'),
        ),
        migrations.AddField(
            model_name='articletypes',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogtypes', verbose_name='المدونة'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.articletypes', verbose_name='نوع المقالة'),
        ),
        migrations.AddField(
            model_name='article',
            name='blogTypes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogtypes', verbose_name='نوع المدونة'),
        ),
    ]
