# Generated by Django 4.1.2 on 2022-10-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articletypes_blogtypes_delete_articletype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
