# Generated by Django 4.1.2 on 2022-10-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_articleviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_Type',
        ),
        migrations.AddField(
            model_name='article',
            name='article_Type',
            field=models.ManyToManyField(to='blog.articletypes', verbose_name='نوع المقالة'),
        ),
    ]
