# Generated by Django 4.1.2 on 2022-10-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_article_article_type_article_article_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='هل الخدمة مفعلة ليظهر على الموقع'),
        ),
    ]
