# Generated by Django 4.1.3 on 2022-11-19 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_alter_article_article_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_visible_to_the_user',
            field=models.BooleanField(default=True, verbose_name='اظهار الخدمة عند المستخدم'),
        ),
        migrations.AddField(
            model_name='article',
            name='save_as_draft',
            field=models.BooleanField(default=False, verbose_name='حفظ كمسودة'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الناشر'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article',
            field=froala_editor.fields.FroalaField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_Type',
            field=models.ManyToManyField(blank=True, to='blog.articletypes', verbose_name='نوع المقالة'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_ar',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_en',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_img',
            field=models.ImageField(blank=True, null=True, upload_to='article/img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='article',
            name='blogTypes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogtypes', verbose_name='نوع المدونة'),
        ),
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='وصف'),
        ),
        migrations.AlterField(
            model_name='article',
            name='desc_ar',
            field=models.TextField(blank=True, null=True, verbose_name='وصف'),
        ),
        migrations.AlterField(
            model_name='article',
            name='desc_en',
            field=models.TextField(blank=True, null=True, verbose_name='وصف'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الصورة'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_desc_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الصورة'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_desc_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الصورة'),
        ),
        migrations.AlterField(
            model_name='article',
            name='keyword',
            field=models.TextField(blank=True, null=True, verbose_name='كلمات مفتاحية'),
        ),
        migrations.AlterField(
            model_name='article',
            name='keyword_ar',
            field=models.TextField(blank=True, null=True, verbose_name='كلمات مفتاحية'),
        ),
        migrations.AlterField(
            model_name='article',
            name='keyword_en',
            field=models.TextField(blank=True, null=True, verbose_name='كلمات مفتاحية'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='عنوان المقالة'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان المقالة'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان المقالة'),
        ),
    ]
