# Generated by Django 4.1.3 on 2022-11-19 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_article_is_visible_to_the_user_article_save_as_draft_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitArticlesForAccept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='الخدمة')),
            ],
        ),
    ]
