# Generated by Django 4.1.3 on 2022-11-19 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_editedarticleswaitforaccept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editedarticleswaitforaccept',
            name='service_Type',
        ),
        migrations.RemoveField(
            model_name='editedarticleswaitforaccept',
            name='storeTypes',
        ),
        migrations.AddField(
            model_name='editedarticleswaitforaccept',
            name='article_Type',
            field=models.ManyToManyField(blank=True, to='blog.articletypes', verbose_name='نوع المقالة'),
        ),
        migrations.AddField(
            model_name='editedarticleswaitforaccept',
            name='blogTypes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogtypes', verbose_name='نوع المدونة'),
        ),
    ]
