# Generated by Django 4.1.3 on 2022-11-19 10:02

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_editedarticleswaitforaccept_service_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editedarticleswaitforaccept',
            name='article_ar',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editedarticleswaitforaccept',
            name='article_en',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editedarticleswaitforaccept',
            name='desc_ar',
            field=models.TextField(blank=True, null=True, verbose_name='وصف'),
        ),
        migrations.AddField(
            model_name='editedarticleswaitforaccept',
            name='desc_en',
            field=models.TextField(blank=True, null=True, verbose_name='وصف'),
        ),
        migrations.AddField(
            model_name='editedarticleswaitforaccept',
            name='img_desc_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الصورة'),
        ),
        migrations.AddField(
            model_name='editedarticleswaitforaccept',
            name='img_desc_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الصورة'),
        ),
        migrations.AddField(
            model_name='editedarticleswaitforaccept',
            name='keyword_ar',
            field=models.TextField(blank=True, null=True, verbose_name='كلمات مفتاحية'),
        ),
        migrations.AddField(
            model_name='editedarticleswaitforaccept',
            name='keyword_en',
            field=models.TextField(blank=True, null=True, verbose_name='كلمات مفتاحية'),
        ),
        migrations.AddField(
            model_name='editedarticleswaitforaccept',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان المقالة'),
        ),
        migrations.AddField(
            model_name='editedarticleswaitforaccept',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان المقالة'),
        ),
    ]
