# Generated by Django 4.1.3 on 2022-11-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_articleviews_city_articleviews_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleviews',
            name='earn_count',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='ربحت من الزيارة'),
        ),
    ]
