# Generated by Django 4.1.3 on 2022-11-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_articleviews_earn_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleviews',
            name='earn_count',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='ربحت من الزيارة'),
        ),
    ]
