# Generated by Django 4.1.2 on 2022-10-28 18:43

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertImageFormatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ar', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('desc', models.TextField()),
                ('desc_ar', models.TextField(null=True)),
                ('desc_en', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='tools/ConvertImageFormatToImage/')),
                ('image_ar', models.ImageField(null=True, upload_to='tools/ConvertImageFormatToImage/')),
                ('image_en', models.ImageField(null=True, upload_to='tools/ConvertImageFormatToImage/')),
                ('from_format', models.CharField(choices=[('png', 'png'), ('jpg', 'jpg'), ('webp', 'webp'), ('ico', 'ico'), ('pdf', 'pdf')], default='png', max_length=50)),
                ('to_format', models.CharField(choices=[('png', 'png'), ('jpg', 'jpg'), ('webp', 'webp'), ('ico', 'ico'), ('pdf', 'pdf')], default='jpg', max_length=50)),
                ('article', froala_editor.fields.FroalaField()),
                ('article_ar', froala_editor.fields.FroalaField(null=True)),
                ('article_en', froala_editor.fields.FroalaField(null=True)),
            ],
        ),
    ]
