# Generated by Django 4.1.2 on 2022-10-28 18:47

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertimageformatmodel',
            name='article',
            field=froala_editor.fields.FroalaField(blank=True, verbose_name='المقالة'),
        ),
        migrations.AlterField(
            model_name='convertimageformatmodel',
            name='article_ar',
            field=froala_editor.fields.FroalaField(blank=True, null=True, verbose_name='المقالة'),
        ),
        migrations.AlterField(
            model_name='convertimageformatmodel',
            name='article_en',
            field=froala_editor.fields.FroalaField(blank=True, null=True, verbose_name='المقالة'),
        ),
        migrations.AlterField(
            model_name='convertimageformatmodel',
            name='desc',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='convertimageformatmodel',
            name='desc_ar',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='convertimageformatmodel',
            name='desc_en',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='convertimageformatmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='tools/ConvertImageFormatToImage/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='convertimageformatmodel',
            name='image_ar',
            field=models.ImageField(blank=True, null=True, upload_to='tools/ConvertImageFormatToImage/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='convertimageformatmodel',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='tools/ConvertImageFormatToImage/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='convertimageformatmodel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='convertimageformatmodel',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='convertimageformatmodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='العنوان'),
        ),
    ]
