# Generated by Django 4.1.2 on 2022-10-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_alter_convertimageformatmodel_article_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المتجر')),
                ('name_ar', models.CharField(max_length=255, null=True, verbose_name='اسم المتجر')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='اسم المتجر')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('desc_ar', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('desc_en', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('img', models.ImageField(blank=True, null=True, upload_to='blogTypes/img/')),
                ('img_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الصورة')),
                ('img_desc_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الصورة')),
                ('img_desc_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الصورة')),
                ('keyword', models.TextField(blank=True, null=True, verbose_name='كلمات مفتاحية')),
                ('keyword_ar', models.TextField(blank=True, null=True, verbose_name='كلمات مفتاحية')),
                ('keyword_en', models.TextField(blank=True, null=True, verbose_name='كلمات مفتاحية')),
                ('redirect_url', models.CharField(max_length=255, unique=True, verbose_name='اسم العنوان الذي تريد التوجه عليه')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='convertimageformatmodel',
            name='keyword',
            field=models.TextField(blank=True, null=True, verbose_name='كلمات مفتاحية'),
        ),
        migrations.AddField(
            model_name='convertimageformatmodel',
            name='keyword_ar',
            field=models.TextField(blank=True, null=True, verbose_name='كلمات مفتاحية'),
        ),
        migrations.AddField(
            model_name='convertimageformatmodel',
            name='keyword_en',
            field=models.TextField(blank=True, null=True, verbose_name='كلمات مفتاحية'),
        ),
    ]
