# Generated by Django 4.1.2 on 2022-11-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_alter_toolsmodel_redirect_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='convertedImageDeleteTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, verbose_name='مسار الملف')),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_date_time', models.DateTimeField(verbose_name='تاريخ الحذف')),
            ],
        ),
    ]
